blog-project/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'^accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),

]

django_tryout/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from first_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^first_app/',include('first_app.urls',namespace='first_app')),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage/',views.form_name_view,name='form_name')
]

first_app/urls.py
from django.conf.urls import url
from first_app import views

# for TEMPLATE TAGGING, Django always look for app_name global variable. Used here in case for a href . <a href="{% url 'first_app:other' %}">The OTHER Page</a>
app_name = 'first_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
    url(r'^register/$',views.register,name='register'),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^cbv/$',views.TemplateViewClass.as_view()),
    url(r'^list/$',views.TopicListView.as_view(),name='list'),
    url(r'^list/(?P<pk>\d+)/$',views.TopicDetailView.as_view(),name='detail'),
    url(r'^create/$',views.TopicCreateView.as_view(),name='create'),
    url(r'^list/update/(?P<pk>\d+)/$',views.TopicUpdateView.as_view(),name='update'),
    url(r'^list/delete/(?P<pk>\d+)/$',views.TopicDeleteView.as_view(),name='delete'),





]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse

# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

    def get_absolute_url(self):
        return reverse("first_app:detail",kwargs={'pk':self.pk})



class Webpage(models.Model):
    topic = models.ForeignKey(Topic,related_name='webpages')
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User) # do not inherit from User here !!!!

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from first_app.models import Topic,UserProfileInfo
from django.contrib.auth.models import User

class NewTopicForm(forms.ModelForm):

    class Meta():
        model = Topic
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


# from django import forms
# from django.core import validators
#
#
# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter email again')
#     text = forms.CharField(widget=forms.Textarea)
#
#     def clean(self):
#         # return all clean data from the Form
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verify_email']
#
#         if email != vmail:
#             raise forms.ValidationError("Make sure emails match !")
#
#     # botcatcher = forms.CharField(
#     #     required=False,
#     #     widget=forms.HiddenInput,
#     #     validators=[validators.MaxLengthValidator(0)]
#     # )
#
#
#     # def clean_botcatcher(self):
#     #     botcatcher = self.cleaned_data['botcatcher']
#     #     if len(botcatcher) > 0 :
#     #         raise forms.ValidationError("Gotcha Bot !")
#     #     return botcatcher

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord
from . import forms
from first_app.forms import NewTopicForm,UserForm,UserProfileInfoForm
# Create your views here.


from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy

from django.http import HttpResponse
from . import models

class TopicListView(ListView):
    context_object_name = 'topics'
    model = models.Topic
    # on default, this automaticaaly returns topic_list context. Topic class is lowercased + '_list'. we can change this by defining context_object_name

class TopicDetailView(DetailView):
    context_object_name = 'topic_detail'
    model = models.Topic
    template_name = 'first_app/topic_detail.html'
    # on default, this automaticaaly returns topic context. Topic class is lowercased . we can change this by defining context_object_name

class TopicCreateView(CreateView):
    fields = ('top_name',)
    model = models.Topic

class TopicUpdateView(UpdateView):
    fields = ('top_name',)
    model = models.Topic

class TopicDeleteView(DeleteView):
    model = models.Topic
    success_url = reverse_lazy("first_app:list")



class CBView(View):

    def get(self,request):
        return HttpResponse("Class based views")

class TemplateViewClass(TemplateView):

    template_name = "first_app/templateview.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "Mero naam"
        return context

def index(request):
    webpages_list = Topic.objects.all()
    date_dict = {'topics' : webpages_list }
    # my_dict = {'insert_me': 'Hello from views.py!'}
    return render(request,'first_app/index.html',context=date_dict)

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        print('$$$',username)
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else :
                return HttpResponse("Account not active")
        else:
            print("Login failed !")
            return HttpResponse("invalid login details provided")

    else:
        return render(request,'first_app/login.html',{})

@login_required # only if user is logged in we do logout. so adding this decorator
def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/registration.html',
                    {
                    'user_form':user_form,
                    'profile_form' : profile_form,
                    'registered' : registered
                    })

def other(request):
    return render(request,'first_app/other.html')

def relative(request):
    return render(request,'first_app/relative.html')

def form_name_view(request):

    form = NewTopicForm()

    if request.method == 'POST':
        form = NewTopicForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error form invalid')

    return render(request,'first_app/form_page.html',{'form':form})

    # form = forms.FormName()
    #
    # if request.method == 'POST':
    #     form = forms.FormName(request.POST)
    #
    #     if form.is_valid():
    #         print("Validaion")
    #         print("NAME " + form.cleaned_data['name'])
    #
    # return render(request,'first_app/form_page.html',{'form':form})

first_app/templates/first_app/first_app_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li ><a class="navbar-brand" href="{% url 'index' %}"></a>BRAND</li>
                    <li ><a class="navbar-brand" href="{% url 'admin:index' %}"></a>ADMIN</li>
                    <li ><a class="navbar-brand" href="{% url 'first_app:other' %}"></a>OTHER</li>
                    <li ><a class="navbar-brand" href="{% url 'first_app:register' %}"></a>Register</li>
                    <li ><a class="navbar-brand" href="{% url 'first_app:list' %}"></a>Topics</li>

                    {% if user.is_authenticated %}
                        <li><a class="navbar-brand" href="{% url 'first_app:user_logout' %}"></a>Logout</li>
                    {% else %}
                        <li><a class="navbar-brand" href="{% url 'first_app:user_login' %}"></a>Login</li>
                    {% endif %}

                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
                <!-- Anything outside here will be inherited -->
            {% endblock %}
        </div>
    </body>
</html>

first_app/templates/first_app/topic_confirm_delete.html
<!DOCTYPE html>
{% extends "first_app/first_app_base.html" %}
{% block body_block %}
    <h1>Delete  {{topic.top_name}}? </h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'first_app:detail' pk=topic.pk %}">Cancel</a>
    </form>
{% endblock %}

first_app/templates/first_app/topic_detail.html
<!DOCTYPE html>
{% extends "first_app/first_app_base.html" %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Welcome to detail of a topic</h1>
        <p>
            Name : {{ topic_detail.top_name }}
        </p>
        <h3>Webpages:</h3>

        {% for webpage in topic_detail.webpages.all %}
            <p>
                {{ webpage.name }}
            </p>
        {% endfor %}

    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'first_app:update' pk=topic_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'first_app:delete' pk=topic_detail.pk %}">Delete</a></p>
    </div>

{% endblock %}

first_app/templates/first_app/topic_form.html
<!DOCTYPE html>
{% extends "first_app/first_app_base.html" %}
{% block body_block %}

    <h1>
        {% if not form.instance.pk %}
            Create
        {% else %}
            Update
        {% endif %}

    </h1>

    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

{% endblock %}

first_app/templates/first_app/topic_list.html
<!DOCTYPE html>
{% extends "first_app/first_app_base.html" %}
{% block body_block %}

    <h1>Welcome to list of topics</h1>
    <ol>
         <!-- on default, TopicListView automaticaaly returns topic_list context. Topic class is lowercased + '_list'. we can change this by defining context_object_name -->
        {% for topic in topics %}
            <h3><li> <a href="{{topic.id}}"> {{topic.top_name}} </a> </li></h3>
        {% endfor %}
    </ol>

{% endblock %}